env = "development"
secret = "abc123"
domain = "localhost"
title = "Bunker System"
[db]
file = "/tmp/bunker.sqlite3"
[http]
host = "localhost"
port = 3000
secure = false
[sshd]
host = "0.0.0.0"
port = 2222
private_key = "/etc/bunker/host_rsa"
replay_dir = "/tmp/bunker-replays"
[ssh]
private_key = "/etc/bunker/id_rsa"
[sandbox]
image = "yanke/bunker-sandbox"
data_dir = "/var/bunker/sandboxdata"
[consul]
enable = false