env = "development"
secret = "abc123"
domain = "localhost"
title = "Bunker System"
[db]
url = "mysql://root@localhost:3306/bunker_dev"
[redis]
url = "redis://localhost:6379"
[http]
host = "localhost"
port = 3000
secure = false
[sshd]
host = "0.0.0.0"
port = 2222
private_key = "/etc/bunker/host_rsa"
[ssh]
private_key = "/etc/bunker/id_rsa"
[sandbox]
image = "ireul/sandbox"
datadir = "/var/bunker/sandboxdata"