env = "development"
secret = "abc123"
domain = "example.com"
title = "Bunker System"
[db]
url = "root@tcp(localhost:3306)/bunker_dev?parseTime=true&charset=utf8mb4,utf8"
[redis]
url = "redis://localhost:6379"
[http]
host = "localhost"
port = 3000
[sshd]
host = "0.0.0.0"
port = 2222
private_key = "/tmp/host_rsa"
[ssh]
private_key = "/tmp/client_rsa"